declare const styles: {
  readonly fontH1: string
  readonly fontH2: string
  readonly fontH3: string
  readonly fontH4: string
  readonly fontH5: string
  readonly fontH6: string
  readonly fontOverline: string
  readonly fontPLarge: string
  readonly fontP: string
  readonly fontPSmall: string
  readonly fontPSmaller: string
  readonly fontLink: string
  readonly fontQuote: string
  readonly fontButton: string
  readonly isMonospace: string
  readonly isSemibold: string
  readonly isMedium: string
  readonly isRegular: string
  readonly isPrimaryText: string
  readonly isSecondaryText: string
  readonly isMuteText: string
  readonly isMuterText: string
  readonly styleLinkInlineLight: string
  readonly light: string
  readonly cta: string
  readonly primary: string
  readonly visited: string
  readonly secondary: string
  readonly remarkEmoji: string
  readonly fontNowrap: string
}
export = styles
