declare const styles: {
  readonly isSlantedTopSmall: string
  readonly isSlantedTopMedium: string
  readonly isSlantedTopLarge: string
  readonly isSlantedTopLarger: string
  readonly fontH1: string
  readonly fontH2: string
  readonly fontH3: string
  readonly fontH4: string
  readonly fontH5: string
  readonly fontH6: string
  readonly fontDisplay: string
  readonly fontOverline: string
  readonly fontPLarge: string
  readonly fontP: string
  readonly fontPSmall: string
  readonly fontPSmaller: string
  readonly fontLink: string
  readonly fontPDisplay: string
  readonly fontQuote: string
  readonly fontButton: string
  readonly fontNav: string
  readonly fontNowrap: string
  readonly isMonospace: string
  readonly isSemibold: string
  readonly isMedium: string
  readonly isRegular: string
  readonly isPrimaryText: string
  readonly isSecondaryText: string
  readonly isMuteText: string
  readonly isMuterText: string
  readonly isThemedPrimary: string
  readonly isGradientPrimary: string
  readonly pill: string
  readonly dot: string
  readonly remarkEmoji: string
  readonly textIsCentered: string
  readonly buttonGroup: string
}
export = styles
