declare const styles: {
  readonly secondary: string
  readonly cta: string
  readonly primary: string
  readonly visited: string
  readonly remarkEmoji: string
  readonly fontBase: string
  readonly fontBold: string
  readonly fontHero: string
  readonly fontH1: string
  readonly fontH2: string
  readonly fontH3: string
  readonly fontH4: string
  readonly fontH5: string
  readonly fontH6: string
  readonly fontOverline: string
  readonly fontSubtitle: string
  readonly fontBtn: string
  readonly fontBtnLg: string
  readonly fontBtnMd: string
  readonly fontBtnSm: string
  readonly fontLink: string
  readonly fontLinkLg: string
  readonly fontLinkMd: string
  readonly fontLinkSm: string
  readonly fontP: string
  readonly fontMono: string
  readonly fontMonoS: string
}
export = styles
