declare const styles: {
  readonly newsletter: string
  readonly textAlign: string
  readonly form: string
  readonly containerFluid: string
  readonly row: string
  readonly topSm: string
  readonly middleSm: string
  readonly bottomSm: string
  readonly justifyCenterSm: string
  readonly mobileOffset64: string
  readonly mobileOffset32: string
  readonly mobileOffset16: string
  readonly mobileOffset8: string
  readonly centerMobile: string
  readonly hiddenSm: string
  readonly hiddenMd: string
  readonly hiddenLg: string
  readonly colSm: string
  readonly colSmOffset: string
  readonly topMd: string
  readonly middleMd: string
  readonly bottomMd: string
  readonly colMd: string
  readonly colMdOffset: string
  readonly topLg: string
  readonly middleLg: string
  readonly bottomLg: string
  readonly colLg: string
  readonly colLgOffset: string
  readonly hiddenXsNext: string
  readonly hiddenSmNext: string
  readonly hiddenMdNext: string
  readonly hiddenLgNext: string
  readonly responsive: string
  readonly embedVideoContainer: string
  readonly youtube: string
  readonly elevationBase: string
  readonly elevationMedium: string
  readonly elevationLarge: string
  readonly elevationXl: string
  readonly elevationXxl: string
  readonly styleLinkInlineLight: string
  readonly light: string
  readonly cta: string
  readonly primary: string
  readonly visited: string
  readonly secondary: string
  readonly remarkEmoji: string
  readonly fontNowrap: string
  readonly fontBold: string
  readonly fontHero: string
  readonly mute85: string
  readonly mute60: string
  readonly mute40: string
  readonly fontH1: string
  readonly fontH2: string
  readonly fontH3: string
  readonly fontH4: string
  readonly fontH5: string
  readonly fontH6: string
  readonly fontQuote: string
  readonly fontOverline: string
  readonly fontBtn: string
  readonly fontLink: string
  readonly fontLinkMd: string
  readonly fontP: string
  readonly fontPLg: string
  readonly fontPSm: string
  readonly fontPXs: string
  readonly fontMono: string
  readonly fontMonoS: string
  readonly fontMenu: string
  readonly fontCategory: string
}
export = styles
